### ISSUE TITLE
JS: create ToDo item card

### ISSUE THREAD

**Issue by ddrummer3993** [ddrummer3993/ToDo-app#4]

**Comment by ddrummer3993** [comment]
- [x] -create HTML card structure via JS
- [x] -includes ToDo item
- [ ] -includes edit button
- [ ] -includes a delete button
- [x] -display small description
